development: &defaults
  consumer_key: jgby2asj6wl872jo
  consumer_secret: mh7cd7aw90uunsnz
  consumer_handler: TamHandler
  site: https://telcoassetmarketplace.com

test:
  <<: *defaults

production:
  <<: *defaults
